apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlgpt-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sqlgpt-api
  template:
    metadata:
      labels:
        app: sqlgpt-api
    spec:
      containers:
        - name: sqlgpt-api
          image: 566057504384.dkr.ecr.ap-south-2.amazonaws.com/sqlgpt-api:latest
          ports:
            - containerPort: 8000