# agents/prompt_enhancer.py

import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv(override=True)

client = Groq(api_key=os.getenv("GROQ_API_KEY"))


def enhance_question(question: str) -> str:
    """
    Rewrites vague user questions into clear, SQL-friendly analytical queries.
    Runs before intent agent — improves everything downstream.
    """

    prompt = f"""You are a data analyst assistant. A user asked a question about NYC taxi data.

Rewrite their question into a clear, complete, SQL-friendly analytical question.

Rules:
- Add missing context (time period, metric, grouping)
- Expand abbreviations and slang
- Make it specific enough to write SQL for
- Keep the same intent — do not change what they are asking
- If question is already clear and complete — return it as-is
- Return ONLY the rewritten question, nothing else

Examples:
"top zones??" → "Which pickup zones had the highest number of trips in September 2025?"
"rides yesterday" → "How many total trips were completed in September 2025?"
"money per area" → "What is the total revenue generated by each pickup borough?"
"uber vs lyft" → "Compare total trips and revenue between Uber and Lyft (FHVHV) in September 2025"
"avg speed manhattan rush hour" → "What is the average trip speed in Manhattan during morning rush hours (7AM-9AM) on weekdays?"

User question: {question}

Rewritten question:"""

    try:
        response = client.chat.completions.create(
            model="meta-llama/llama-4-scout-17b-16e-instruct",
            messages=[{"role": "user", "content": prompt}],
            temperature=0
        )
        enhanced = response.choices[0].message.content.strip()
        print(f"  [Enhancer] '{question}' → '{enhanced}'")
        return enhanced

    except Exception as e:
        print(f"  [Enhancer ERROR] {e} — using original question")
        return question