name: CI/CD to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  EKS_CLUSTER: ${{ secrets.EKS_CLUSTER }}

  IMAGE_API: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/sqlgpt-api
  IMAGE_UI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/sqlgpt-ui

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # API
      - name: Build & Push API
        run: |
          docker build -t $IMAGE_API:$GITHUB_SHA -f Dockerfile.api .
          docker push $IMAGE_API:$GITHUB_SHA

      # UI
      - name: Build & Push UI
        run: |
          docker build -t $IMAGE_UI:$GITHUB_SHA -f Dockerfile.ui .
          docker push $IMAGE_UI:$GITHUB_SHA

      - name: Connect to EKS
        run: |
          aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $EKS_CLUSTER

      - name: Deploy
        run: |
          kubectl apply -f k8s/

          kubectl set image deployment/sqlgpt-api \
          sqlgpt-api=$IMAGE_API:$GITHUB_SHA

          kubectl set image deployment/sqlgpt-ui \
          sqlgpt-ui=$IMAGE_UI:$GITHUB_SHA
      - name: Debug Kubernetes
        run: |
          echo "===== CONTEXT ====="
          kubectl config current-context

          echo "===== NODES ====="
          kubectl get nodes

          echo "===== DEPLOYMENTS ====="
          kubectl get deployments

          echo "===== PODS ====="
          kubectl get pods -o wide

          echo "===== SERVICES ====="
          kubectl get svc

          echo "===== DESCRIBE UI SERVICE ====="
          kubectl describe svc sqlgpt-ui-service

          echo "===== EVENTS ====="
          kubectl get events --sort-by=.metadata.creationTimestamp